{
 "title": "Telegraf metrics",
 "description": "InfluxDB dashboards for telegraf metrics",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$server",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "server",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "system_uptime",
     "query": "SELECT last(\"uptime\") AS \"value\" FROM \"system\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$server",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "repeat": "server",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "query": "SELECT mean(\"free\") AS \"value\" FROM \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" = '/' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$server",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "repeat": "server",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "system_uptime",
     "query": "SELECT mean(\"available_percent\") AS \"value\" FROM \"mem\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "SYSTEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "SELECT mean(load1) as load1,mean(load5) as load5,mean(load15) as load15 FROM \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT mean(usage_idle) as \"idle\", mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and  cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_path : $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "io_reads",
     "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "swap_in",
     "query": "SELECT mean(free) as \"free\", mean(used) as \"used\", mean(total) as \"total\" FROM \"swap\" WHERE  $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap I/O bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "swap_in",
     "query": "SELECT mean(\"in\") as \"in\", mean(\"out\") as \"out\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "JAVA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Java Threading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host:DaemonThreadCount",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"DaemonThreadCount\" FROM java_threading WHERE $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host:PeakThread",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"PeakThreadCount\"  FROM java_threading WHERE $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host:TotalStartedThreads",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"TotalStartedThreadCount\"  FROM java_threading WHERE $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host:ThreadCount",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"ThreadCount\"  FROM java_threading WHERE $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Java Class Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host:LoadedClassCount",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LoadedClassCount FROM java_class_loading WHERE $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host:TotalLoadedClassCount",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT TotalLoadedClassCount FROM java_class_loading WHERE $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Java Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host:HeapMemoryUsage",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT HeapMemoryUsage.used FROM java_memory WHERE $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host:NonHeapMemoryUsage",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT NonHeapMemoryUsage.used FROM java_memory WHERE $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Java Memory Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host:PeakUsage",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT PeakUsage.used FROM java_memory_pool where $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host:Usage",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT Usage.used FROM java_memory_pool where $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}